# Generated by Django 3.2.5 on 2021-07-19 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='score',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='review',
        ),
    ]
