# Generated by Django 3.2.5 on 2021-07-18 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='strip_token',
            new_name='stripe_token',
        ),
    ]
